# Generated by Django 5.2.5 on 2025-08-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DRF_App', '0002_alter_students_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='emp_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
